In [1]:
import pandas as pd

In [3]:
csv_path = "/home/mrahma56/Classification-Consistency/Output/Annotation/Annotation_irony_greek_deepseek_full_sample_translations.csv"
# csv_path = "/home/mrahma56/Classification-Consistency/Output/Annotation/Logs/annotation_log_20250821T132548Z.csv"
df = pd.read_csv(csv_path)
df.tail(10)

,original_text,literal_translation,cultural_translation,gpt_label_literal,claude_label_literal,deepseek_label_literal,literal_machine_label,gpt_label_cultural,claude_label_cultural,deepseek_label_cultural,cultural_machine_label
0,I literally get to pamper myself all day tomor...,Κυριολεκτικά θα μπορέσω να περιποιηθώ τον εαυτ...,Αύριο θα χαλαρώσω όλη μέρα και θα περάσω υπέρο...,3,1,1,1,0,1,1,1
1,@mel78carey I'm not a Lohan anymore :grinning_...,@mel78carey Δεν είμαι πια μια Lohan :grinning_...,@mel78carey Δεν είμαι πια στα πλαίσια της Loha...,0,0,1,0,0,0,1,0
2,stl.You Will Never Win Again RT @viggie_kopite...,stl.Δεν θα κερδίσετε ποτέ ξανά RT @viggie_kopi...,stl.Δεν θα ξανακερδίσετε ποτέ RT @viggie_kopit...,2,1,1,1,2,1,1,1
3,Tonight's family bonding presents a dark quite...,Η οικογενειακή σύνδεση απόψε παρουσιάζει ένα σ...,Απόψε η οικογενειακή συγκέντρωση περιλαμβάνει ...,0,1,1,1,0,1,1,1
4,All I wanted was to see you,Το μόνο που ήθελα ήταν να σε δω,Δεν ήθελα τίποτα άλλο παρά μόνο να σε δω,0,-1,0,0,0,-1,0,0

In [9]:
len(df)

5

In [3]:
csv_path = "/home/mrahma56/Classification-Consistency/Output/Annotation/Logs/annotation_log_literal_20250821T140839Z.csv"
df = pd.read_csv(csv_path)
df.head(10)

,timestamp,file_name,sample_idx,sample_name,model_name,try_idx,raw_output
0,2025-08-21T09:08:40,deptweet_bengali_nllb_full_translations.csv,0,The mainstream has been dead to me for many ye...,gpt:gpt-4.1-mini,0,label: 3
1,2025-08-21T09:08:43,deptweet_bengali_nllb_full_translations.csv,0,The mainstream has been dead to me for many ye...,deepseek:deepseek-chat,0,label: 3
2,2025-08-21T09:08:44,deptweet_bengali_nllb_full_translations.csv,1,no clue but my new friend likes it and said it...,gpt:gpt-4.1-mini,0,label: 0
3,2025-08-21T09:08:47,deptweet_bengali_nllb_full_translations.csv,1,no clue but my new friend likes it and said it...,deepseek:deepseek-chat,0,label: 0
4,2025-08-21T09:08:48,deptweet_bengali_nllb_full_translations.csv,2,Why can’t I just fall asleep I’m literally so ...,gpt:gpt-4.1-mini,0,label: 1
5,2025-08-21T09:08:51,deptweet_bengali_nllb_full_translations.csv,2,Why can’t I just fall asleep I’m literally so ...,deepseek:deepseek-chat,0,label: 1
6,2025-08-21T09:08:52,deptweet_bengali_nllb_full_translations.csv,3,Agree with you on all points. My son who was s...,gpt:gpt-4.1-mini,0,label: 1
7,2025-08-21T09:08:56,deptweet_bengali_nllb_full_translations.csv,3,Agree with you on all points. My son who was s...,deepseek:deepseek-chat,0,label: 0
8,2025-08-21T09:08:56,deptweet_bengali_nllb_full_translations.csv,3,Agree with you on all points. My son who was s...,claude:claude-3-5-haiku-20241022,0,label: 1
9,2025-08-21T09:08:57,deptweet_bengali_nllb_full_translations.csv,4,I was there on a Saturday about a month ago an...,gpt:gpt-4.1-mini,0,label: 0

In [33]:
# df['raw_output'].iloc[0]